version: '3'
services: 
  aiko-server: 
    image: aikocute/aikocutehotme:latest
    environment:
      - FORMAT=yml
    volumes:
      - ./config:/etc/Aiko-Server/
    restart: always
    network_mode: host