version: '3'
services: 
  aiko-server: 
    image: aikocute/aikocutehotme:latest
    environment:
      - FORMAT=yml # format of config file, yml or json
      - DOMAIN=example.com # domain for TLS certificate
      - EXPIRE=90 # days before certificate expires
    volumes:
      - ./config:/etc/Aiko-Server/
    restart: always
    network_mode: host