Nodes:
  - PanelType: "AikoPanelv2" # Panel type: AikoPanel, AikoPanelv2
    ApiConfig:
      ApiHost: "http://127.0.0.1:667"
      ApiKey: "123"
      NodeID: 41
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
      RuleListPath: # /etc/Aiko-Server/rulelist # Path of rulelist
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file. Choose "none" will forcedly disable the tls config.
        CertFile: /etc/Aiko-Server/cert/aiko_server.cert # Provided if the CertMode is file
        KeyFile: /etc/Aiko-Server/cert/aiko_server.key
